<a href="https://colab.research.google.com/github/Pravallika1234uppala/ML/blob/main/ML%20Models/Supervised%20Learning/Classification%20%26%20Regression/K%20Nearest%20Neighbour/KNN%20Classification/K_Nearest_Neighbour_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## K NEAREST NEIGHBOUR CLASSIFIER:

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline

### BINARY CLASSIFICATION:

In [2]:
from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=3000, #3000 observations or data points
    n_features=4, #4 input features
    n_redundant=1,
    n_classes=2, #binary target/label
    random_state=89
)

In [3]:
X

array([[ 0.19796014, -1.58259011, -0.49558685,  0.24560592],
       [ 0.78285662, -0.69272531, -1.15546185, -1.18488995],
       [-0.62128236,  0.46786825, -1.16163274, -1.87397072],
       ...,
       [-1.47025051,  1.83268066,  2.30675691,  2.1017821 ],
       [ 0.70998124,  0.9247321 ,  1.08393575,  0.95034504],
       [ 0.13026801, -1.56051503, -2.15808514, -2.0566565 ]])

In [4]:
y

array([0, 1, 1, ..., 1, 1, 0])

In [5]:
df = pd.DataFrame(X)

In [6]:
df

0         1         2         3
0     0.197960 -1.582590 -0.495587  0.245606
1     0.782857 -0.692725 -1.155462 -1.184890
2    -0.621282  0.467868 -1.161633 -1.873971
3    -1.485208  0.744210 -0.788828 -1.522655
4    -1.127394  1.177465  1.424261  1.270779
...        ...       ...       ...       ...
2995 -1.645575  2.374292  0.161370 -1.170096
2996  1.139410  0.739016  0.799626  0.667747
2997 -1.470251  1.832681  2.306757  2.101782
2998  0.709981  0.924732  1.083936  0.950345
2999  0.130268 -1.560515 -2.158085 -2.056656

[3000 rows x 4 columns]

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=42)

In [8]:
X_train

array([[-1.36436706, -1.83817892, -0.70598674,  0.10575777],
       [-0.30784308,  1.21531891,  0.98761588,  0.64730636],
       [-0.70094679,  1.00645358,  1.12456909,  0.95837628],
       ...,
       [ 0.69237357, -0.96340545,  0.33484504,  1.02604338],
       [-1.29615668, -1.06983735, -1.3311336 , -1.20565387],
       [ 0.3647845 ,  2.04396816,  0.38735015, -0.66520811]])

In [9]:
y_train

array([0, 1, 1, ..., 0, 0, 1])

In [10]:
X_test

array([[ 0.95154118, -1.58867531, -2.30266759, -2.23923805],
       [ 1.53106638, -0.05628971,  0.4513158 ,  0.65448622],
       [ 0.85032273,  0.44453142,  0.42142379,  0.31963756],
       ...,
       [-0.82023454,  1.0844    ,  1.25755428,  1.09579294],
       [-0.8366431 , -1.35121921, -1.20463462, -0.8664554 ],
       [-0.74726594, -0.95862884,  0.36172922,  1.06026276]])

In [11]:
y_test

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,

In [12]:
from sklearn.neighbors import KNeighborsClassifier

'''
n_neighbors(k)=5 default

weights-uniform and distance.
if all points weighted equally - uniform
if the weighting the points is inverse of their distance(so closer neighbours have greate influyence)


algorithm- need to find distance from new point to every other points to find 5 nearest neighbors.
These algorithms creates a binary tree.
so, due to decrease in search size bcz of trees Time complexity decreases and optimization increases.
can use:

ball_tree
kd_tree
brute
auto(based on the dataset any parameters are selected.)


p-2 (default and int)
This indicates. euclidean distance.
2-euclidean distance by default
if 1 - manhattan distance.

'''

'\nn_neighbors(k)=5 default\n\nweights-uniform and distance.\nif all points weighted equally - uniform\nif the weighting the points is inverse of their distance(so closer neighbours have greate influyence)\n\n\nalgorithm- need to find distance from new point to every other points to find 5 nearest neighbors.\nThese algorithms creates a binary tree.\nso, due to decrease in search size bcz of trees Time complexity decreases and optimization increases.\ncan use:\n\nball_tree\nkd_tree\nbrute\nauto(based on the dataset any parameters are selected.)\n\n\np-2 (default and int)\nThis indicates. euclidean distance.\n2-euclidean distance by default\nif 1 - manhattan distance.\n\n'

In [13]:
classmodel = KNeighborsClassifier() #all default p=2, k=5, algorithm=auto
#if feastures are randomly distribution in features dimensions euclidean distance is prefereed.


In [14]:
classmodel

KNeighborsClassifier()

In [15]:
classmodel.fit(X_train, y_train)

KNeighborsClassifier()

In [16]:
classmodel.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [17]:
y_pred = classmodel.predict(X_test)

In [18]:
error = np.average(y_test-y_pred)
print(error)

-0.013333333333333334


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(f"Score: {accuracy_score(y_test, y_pred)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification Report: \n{classification_report(y_test, y_pred)}")

Score: 0.8933333333333333
Confusion matrix: 
[[374  54]
 [ 42 430]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      0.87      0.89       428
           1       0.89      0.91      0.90       472

    accuracy                           0.89       900
   macro avg       0.89      0.89      0.89       900
weighted avg       0.89      0.89      0.89       900



### GRID SEARCH CV:

In [21]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
params = {
    'n_neighbors': [2,4,5,7,8,9],  # K values
    'weights': ['uniform', 'distance'],  # strategies of weights
    'metric': ['euclidean', 'manhattan', 'minkowski'],  # Distance measures
    'p': [1, 2]  # power parameter ( distance behavior)
}

grid_knc = GridSearchCV(KNeighborsClassifier(), param_grid=params, cv=5, scoring='accuracy', n_jobs=-1)
grid_knc.fit(X_train, y_train)


print(f"Best Parameters: {grid_knc.best_params_}")
print(f"Best Cross-Validation Accuracy: {grid_knc.best_score_:.4f}")


best_knn = grid_knc.best_estimator_
test_accuracy = best_knn.score(X_test, y_test)
print(f"Test Accuracy: {test_accuracy:.4f}")

Best Parameters: {'metric': 'euclidean', 'n_neighbors': 9, 'p': 1, 'weights': 'distance'}
Best Cross-Validation Accuracy: 0.8990
Test Accuracy: 0.8967
