<a href="https://colab.research.google.com/github/Pravallika1234uppala/ML/blob/main/ML%20Models/Supervised%20Learning/Classification%20%26%20Regression/K%20Nearest%20Neighbour/KNN%20Regression/K_Nearest_Neighbour_Regressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## K NEAREST NEIGHBOUR REGRESSOR:

In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline

In [25]:
from sklearn.datasets import make_regression

X, y = make_regression(
    n_samples=3000, #3000 observations or data points
    n_features=3, #3 input features
    noise=10, #Random Gaussian noise is added to y, making the relationship less
    #perfect (more like real-world data).
    random_state=42
)

In [26]:
X

array([[-1.33314801, -0.24733596,  0.33271933],
       [-0.37326825,  0.64451849, -1.02740355],
       [-0.72574381,  0.18676676,  0.51765902],
       ...,
       [-0.12372895, -0.39767969, -0.38281719],
       [ 0.50427075,  0.5214494 , -0.36567708],
       [ 0.02538842, -1.91967316, -0.04541122]])

In [27]:
y

array([-66.60915204, -93.25930659,   6.21392987, ..., -61.09848557,
        28.77917429, -53.55422448])

In [34]:
df1 = pd.DataFrame(X)
df2 = pd.DataFrame(y)

In [40]:
df = pd.concat([df1, df2], axis=1, ignore_index=True)

In [41]:
df

0         1         2           3
0    -1.333148 -0.247336  0.332719  -66.609152
1    -0.373268  0.644518 -1.027404  -93.259307
2    -0.725744  0.186767  0.517659    6.213930
3     1.203884 -0.139446  0.615771  125.120070
4     0.459972 -0.677715 -0.753418  -37.056550
...        ...       ...       ...         ...
2995 -0.909690  0.759500 -1.050055 -108.344125
2996 -0.601944 -0.633231 -0.060038  -61.330068
2997 -0.123729 -0.397680 -0.382817  -61.098486
2998  0.504271  0.521449 -0.365677   28.779174
2999  0.025388 -1.919673 -0.045411  -53.554224

[3000 rows x 4 columns]

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=42)

In [43]:
X_train

array([[-0.31508193, -0.24143056,  1.44882011],
       [ 2.04207604,  0.27735846,  0.10343813],
       [ 0.0693698 ,  0.19259692, -0.22104246],
       ...,
       [-0.3011037 , -1.47852199, -0.11564828],
       [-0.30046595, -1.00560138, -0.07938842],
       [ 0.5206895 , -1.07953285,  0.46643129]])

In [44]:
y_train

array([ 68.89437426, 158.93887782,  -1.01251438, ..., -79.10358277,
       -53.13468222,  42.40335715])

In [45]:
X_test

array([[-0.3054447 , -1.72918289,  0.96415588],
       [-0.17387382,  1.33859214, -0.01035229],
       [ 0.88707978,  0.28677411, -1.19796643],
       ...,
       [-0.75574516,  0.53650984, -0.17495976],
       [-0.66733338, -2.24191593,  0.09982632],
       [ 0.70253331, -1.33244835, -0.36778453]])

In [46]:
y_test

array([-3.04593162e+00,  2.54539515e+01, -2.80912601e+01, -3.80719698e+01,
       -2.55052075e+01,  3.79228385e+01, -1.77533049e+02,  2.36117727e+00,
       -6.01451716e+01,  9.53643325e+01,  2.70932477e+01,  2.83267060e+01,
       -1.26890084e+02, -1.63212781e+01, -9.22802223e+01,  9.06109472e+01,
       -1.67076419e+02, -3.96056411e+01, -4.19111029e+01, -1.67964904e+02,
        1.62334247e+02, -2.13966904e+01, -1.43481635e+02,  1.57890407e+02,
       -1.59299885e+02, -4.93764659e+01,  1.27138271e+02, -3.98586735e+01,
       -5.48463779e+01, -3.54946724e+01,  2.19693188e+02, -1.89672298e+02,
        2.70366578e+01,  4.90980700e+01,  1.62003062e+02,  3.95576640e+01,
        4.33600162e+01,  4.76988547e+01, -1.45363038e+02,  7.88104005e+01,
        1.98082136e+01, -1.42704676e+01,  5.67909662e+00, -7.15946049e+01,
        6.67426191e+01, -2.24635502e+01, -1.53329969e+01, -1.57344466e+02,
        2.44391067e+01, -1.20102523e+02,  7.84982317e+01,  4.24343935e+01,
        1.10244410e+02, -

In [47]:
from sklearn.neighbors import KNeighborsRegressor

'''
n_neighbors(k)=5 default

weights-uniform and distance.
if all points weighted equally - uniform
if the weighting the points is inverse of their distance(so closer neighbours have greate influyence)


algorithm- need to find distance from new point to every other points to find 5 nearest neighbors.
These algorithms creates a binary tree.
so, due to decrease in search size bcz of trees Time complexity decreases and optimization increases.
can use:

ball_tree
kd_tree
brute
auto(based on the dataset any parameters are selected.)


p-2 (default and int)
This indicates. euclidean distance.
2-euclidean distance by default
if 1 - manhattan distance.

'''

'\nn_neighbors(k)=5 default\n\nweights-uniform and distance.\nif all points weighted equally - uniform\nif the weighting the points is inverse of their distance(so closer neighbours have greate influyence)\n\n\nalgorithm- need to find distance from new point to every other points to find 5 nearest neighbors.\nThese algorithms creates a binary tree.\nso, due to decrease in search size bcz of trees Time complexity decreases and optimization increases.\ncan use:\n\nball_tree\nkd_tree\nbrute\nauto(based on the dataset any parameters are selected.)\n\n\np-2 (default and int)\nThis indicates. euclidean distance.\n2-euclidean distance by default\nif 1 - manhattan distance.\n\n'

In [48]:
regmodel = KNeighborsRegressor(n_neighbors=7) #all default p=2, k=5, algorithm=auto
#if feastures are randomly distribution in features dimensions euclidean distance is prefereed.


In [49]:
regmodel

KNeighborsRegressor(n_neighbors=7)

In [50]:
regmodel.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=7)

In [51]:
regmodel.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 7,
 'p': 2,
 'weights': 'uniform'}

In [52]:
y_pred = regmodel.predict(X_test)

In [53]:
error = np.average(y_test-y_pred)
print(error)

-0.6836390962215816


In [54]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print(f"Score: {r2_score(y_test, y_pred)}")
print(f"mean absolute error: \n{mean_absolute_error(y_test, y_pred)}")
print(f"mean square error: \n{mean_squared_error(y_test, y_pred)}")

Score: 0.9764134731756482
mean absolute error: 
12.09011908543955
mean square error: 
273.8638007131123


### GRID SEARCH CV:

In [56]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
params = {
    'n_neighbors': [2,4,5,7,8,9],  # K values
    'weights': ['uniform', 'distance'],  # strategies of weights
    'metric': ['euclidean', 'manhattan', 'minkowski'],  # Distance measures
    'p': [1, 2]  # power parameter ( distance behavior)
}

grid_knr = GridSearchCV(KNeighborsRegressor(), param_grid=params, cv=5, scoring='accuracy', n_jobs=-1)
grid_knr.fit(X_train, y_train)


print(f"Best Parameters: {grid_knr.best_params_}")
print(f"Best Cross-Validation Accuracy: {grid_knr.best_score_:.4f}")


best_knn = grid_knr.best_estimator_
test_accuracy = best_knn.score(X_test, y_test)
print(f"Test Accuracy: {test_accuracy:.4f}")

Best Parameters: {'metric': 'euclidean', 'n_neighbors': 2, 'p': 1, 'weights': 'uniform'}
Best Cross-Validation Accuracy: nan
Test Accuracy: 0.9703
